### ISSUE TITLE
Not working with classes

### ISSUE THREAD

**Issue by xelexin** [bigbrozer/atom-aligner-puppet#1]
The aligner is not working with Class, for example:

```
class xxx{
  package { 'aaa':
    ensure => present,
    name => $ccc,
    before => Class['bbb'],
  }
}
```

**Comment by bigbrozer** [comment]
If I use that code, select whole and apply aligner with `ctrl + alt + /` it aligns attribute assignments `=>` correctly:

```
class xxx{
  package { 'aaa':
    ensure => present,
    name   => $ccc,
    before => Class['bbb'],
  }
}
```

Or does I missunderstand something ?

**Comment by xelexin** [comment]
Yeah, my bad. Somthing goes wrong with my atom, sorry :)
