### ISSUE TITLE
Unquoted strings are badly aligned.

### ISSUE THREAD

**Issue by psychonaut** [bigbrozer/atom-aligner-puppet#2]
See screencast, unqoted strings are valid in puppet.

![nagranie ekranu z 15 12 2015 10-07-17](https://cloud.githubusercontent.com/assets/807289/11806542/1b65b81e-a314-11e5-86d0-e006a5695056.gif)

**Comment by bigbrozer** [comment]
Uh oh... I'm able to reproduce it, I will check on it. Thx.

**Comment by pdaugavietis** [comment]
Same with numerics with no strings.   when i put quotes around the numbers, the alignment works.   Also not for arrays (wrapped with "[...]")...

**Comment by bigbrozer** [comment]
Sorry guys, I have taken my time on this... not easy to troubleshoot.
I think I have found something interesting but I may need the help of the nice people behind atom/language-puppet.
